var searchData=
[
  ['referencecounter_11373',['ReferenceCounter',['../classSAMRAI_1_1tbox_1_1ReferenceCounter.html',1,'SAMRAI::tbox']]],
  ['referencevalues_11374',['ReferenceValues',['../structIBTK_1_1FEValues_1_1ReferenceValues.html',1,'IBTK::FEValues']]],
  ['refinealgorithm_11375',['RefineAlgorithm',['../classSAMRAI_1_1xfer_1_1RefineAlgorithm.html',1,'SAMRAI::xfer']]],
  ['refinealgorithm_3c_20ndim_20_3e_11376',['RefineAlgorithm&lt; NDIM &gt;',['../classSAMRAI_1_1xfer_1_1RefineAlgorithm.html',1,'SAMRAI::xfer']]],
  ['refineclasses_11377',['RefineClasses',['../classSAMRAI_1_1xfer_1_1RefineClasses.html',1,'SAMRAI::xfer']]],
  ['refinecopytransaction_11378',['RefineCopyTransaction',['../classSAMRAI_1_1xfer_1_1RefineCopyTransaction.html',1,'SAMRAI::xfer']]],
  ['refineoperator_11379',['RefineOperator',['../classSAMRAI_1_1xfer_1_1RefineOperator.html',1,'SAMRAI::xfer']]],
  ['refineoperator_3c_20ndim_20_3e_11380',['RefineOperator&lt; NDIM &gt;',['../classSAMRAI_1_1xfer_1_1RefineOperator.html',1,'SAMRAI::xfer']]],
  ['refinepatchstrategy_11381',['RefinePatchStrategy',['../classSAMRAI_1_1xfer_1_1RefinePatchStrategy.html',1,'SAMRAI::xfer']]],
  ['refinepatchstrategy_3c_20ndim_20_3e_11382',['RefinePatchStrategy&lt; NDIM &gt;',['../classSAMRAI_1_1xfer_1_1RefinePatchStrategy.html',1,'SAMRAI::xfer']]],
  ['refinepatchstrategyset_11383',['RefinePatchStrategySet',['../classIBTK_1_1RefinePatchStrategySet.html',1,'IBTK']]],
  ['refineschedule_11384',['RefineSchedule',['../classSAMRAI_1_1xfer_1_1RefineSchedule.html',1,'SAMRAI::xfer']]],
  ['refinetimetransaction_11385',['RefineTimeTransaction',['../classSAMRAI_1_1xfer_1_1RefineTimeTransaction.html',1,'SAMRAI::xfer']]],
  ['refinetransactionfactory_11386',['RefineTransactionFactory',['../classSAMRAI_1_1xfer_1_1RefineTransactionFactory.html',1,'SAMRAI::xfer']]],
  ['regriddata_11387',['RegridData',['../structIBAMR_1_1IBExplicitHierarchyIntegrator_1_1RegridData.html',1,'IBAMR::IBExplicitHierarchyIntegrator']]],
  ['relaunchablejob_11388',['RelaunchableJob',['../classSAMRAI_1_1tbox_1_1RelaunchableJob.html',1,'SAMRAI::tbox']]],
  ['relaxationlsbccoefs_11389',['RelaxationLSBcCoefs',['../classIBAMR_1_1RelaxationLSBcCoefs.html',1,'IBAMR']]],
  ['relaxationlsmethod_11390',['RelaxationLSMethod',['../classIBAMR_1_1RelaxationLSMethod.html',1,'IBAMR']]],
  ['restartcleaner_11391',['RestartCleaner',['../classIBTK_1_1RestartCleaner.html',1,'IBTK']]],
  ['restartitem_11392',['RestartItem',['../structSAMRAI_1_1tbox_1_1RestartManager_1_1RestartItem.html',1,'SAMRAI::tbox::RestartManager']]],
  ['restartmanager_11393',['RestartManager',['../classSAMRAI_1_1tbox_1_1RestartManager.html',1,'SAMRAI::tbox']]],
  ['rng_11394',['RNG',['../classIBAMR_1_1RNG.html',1,'IBAMR']]],
  ['robinbccoefstrategy_11395',['RobinBcCoefStrategy',['../classSAMRAI_1_1solv_1_1RobinBcCoefStrategy.html',1,'SAMRAI::solv']]],
  ['robinbccoefstrategy_3c_20ndim_20_3e_11396',['RobinBcCoefStrategy&lt; NDIM &gt;',['../classSAMRAI_1_1solv_1_1RobinBcCoefStrategy.html',1,'SAMRAI::solv']]],
  ['robinphysbdrypatchstrategy_11397',['RobinPhysBdryPatchStrategy',['../classIBTK_1_1RobinPhysBdryPatchStrategy.html',1,'IBTK']]],
  ['rodspec_11398',['RodSpec',['../structIBAMR_1_1IBRedundantInitializer_1_1RodSpec.html',1,'IBAMR::IBRedundantInitializer']]]
];
