var searchData=
[
  ['unary_5fcompose_0',['unary_compose',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a08462.html',1,'__gnu_cxx']]],
  ['unary_5ffunction_1',['unary_function',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a06746.html',1,'std']]],
  ['unary_5ffunction_3c_20_5f_5fgnu_5fcxx_3a_3athrow_5fvalue_5flimit_2c_20size_5ft_20_3e_2',['unary_function&lt; __gnu_cxx::throw_value_limit, size_t &gt;',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a06746.html',1,'std']]],
  ['unary_5ffunction_3c_20_5f_5fgnu_5fcxx_3a_3athrow_5fvalue_5frandom_2c_20size_5ft_20_3e_3',['unary_function&lt; __gnu_cxx::throw_value_random, size_t &gt;',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a06746.html',1,'std']]],
  ['unary_5ffunction_3c_20_5foperation_3a_3afirst_5fargument_5ftype_2c_20_5foperation_3a_3aresult_5ftype_20_3e_4',['unary_function&lt; _Operation::first_argument_type, _Operation::result_type &gt;',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a06746.html',1,'std']]],
  ['unary_5ffunction_3c_20_5foperation_3a_3asecond_5fargument_5ftype_2c_20_5foperation_3a_3aresult_5ftype_20_3e_5',['unary_function&lt; _Operation::second_argument_type, _Operation::result_type &gt;',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a06746.html',1,'std']]],
  ['unary_5ffunction_3c_20_5fpredicate_3a_3aargument_5ftype_2c_20bool_20_3e_6',['unary_function&lt; _Predicate::argument_type, bool &gt;',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a06746.html',1,'std']]],
  ['unary_5ffunction_3c_20_5ftp_20_2a_2c_20_5fret_20_3e_7',['unary_function&lt; _Tp *, _Ret &gt;',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a06746.html',1,'std']]],
  ['unary_5ffunction_3c_20_5ftp_2c_20_5fret_20_3e_8',['unary_function&lt; _Tp, _Ret &gt;',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a06746.html',1,'std']]],
  ['unary_5ffunction_3c_20_5ftp_2c_20_5ftp_20_3e_9',['unary_function&lt; _Tp, _Tp &gt;',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a06746.html',1,'std']]],
  ['unary_5ffunction_3c_20_5ftp_2c_20bool_20_3e_10',['unary_function&lt; _Tp, bool &gt;',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a06746.html',1,'std']]],
  ['unary_5ffunction_3c_20const_20_5ftp_20_2a_2c_20_5fret_20_3e_11',['unary_function&lt; const _Tp *, _Ret &gt;',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a06746.html',1,'std']]],
  ['unary_5fnegate_12',['unary_negate',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a06986.html',1,'std']]],
  ['unbalanced_5ftag_13',['unbalanced_tag',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a09022.html',1,'__gnu_parallel']]],
  ['underflow_5ferror_14',['underflow_error',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a02914.html',1,'std']]],
  ['underlying_5ftype_15',['underlying_type',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a03678.html',1,'std']]],
  ['uniform_5fint_5fdistribution_16',['uniform_int_distribution',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a07498.html',1,'std']]],
  ['uniform_5freal_5fdistribution_17',['uniform_real_distribution',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a05490.html',1,'std']]],
  ['unique_5flock_18',['unique_lock',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a07506.html',1,'std']]],
  ['unique_5fptr_19',['unique_ptr',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a07518.html',1,'std']]],
  ['unique_5fptr_3c_20_5ftp_5b_5d_2c_20_5fdp_20_3e_20',['unique_ptr&lt; _Tp[], _Dp &gt;',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a07522.html',1,'std']]],
  ['unique_5fptr_3c_20samrai_3a_3amesh_3a_3astandardtagandinitstrategy_3c_20ndim_20_3e_20_3e_21',['unique_ptr&lt; SAMRAI::mesh::StandardTagAndInitStrategy&lt; NDIM &gt; &gt;',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a07518.html',1,'std']]],
  ['unique_5fptr_3c_20samrai_3a_3asolv_3a_3apoissonspecifications_20_3e_22',['unique_ptr&lt; SAMRAI::solv::PoissonSpecifications &gt;',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a07518.html',1,'std']]],
  ['unique_5fptr_3c_20samrai_3a_3asolv_3a_3arobinbccoefstrategy_3c_20ndim_20_3e_20_3e_23',['unique_ptr&lt; SAMRAI::solv::RobinBcCoefStrategy&lt; NDIM &gt; &gt;',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a07518.html',1,'std']]],
  ['unique_5fptr_3c_20samrai_3a_3axfer_3a_3acoarsenpatchstrategy_3c_20ndim_20_3e_20_3e_24',['unique_ptr&lt; SAMRAI::xfer::CoarsenPatchStrategy&lt; NDIM &gt; &gt;',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a07518.html',1,'std']]],
  ['unique_5fptr_3c_20samrai_3a_3axfer_3a_3arefinepatchstrategy_3c_20ndim_20_3e_20_3e_25',['unique_ptr&lt; SAMRAI::xfer::RefinePatchStrategy&lt; NDIM &gt; &gt;',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a07518.html',1,'std']]],
  ['unique_5fptr_3c_20std_3a_3abasic_5fofstream_20_3e_26',['unique_ptr&lt; std::basic_ofstream &gt;',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a07518.html',1,'std']]],
  ['unordered_5fmap_27',['unordered_map',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a08398.html',1,'std::__debug::unordered_map&lt; typename _Key, typename _Tp, typename _Hash, typename _Pred, typename _Alloc &gt;'],['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a07538.html',1,'std::unordered_map&lt; typename _Key, typename _Tp, typename _Hash, typename _Pred, typename _Alloc &gt;']]],
  ['unordered_5fmultimap_28',['unordered_multimap',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a07534.html',1,'std::unordered_multimap&lt; typename _Key, typename _Tp, typename _Hash, typename _Pred, typename _Alloc &gt;'],['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a08402.html',1,'std::__debug::unordered_multimap&lt; typename _Key, typename _Tp, typename _Hash, typename _Pred, typename _Alloc &gt;']]],
  ['unordered_5fmultiset_29',['unordered_multiset',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a08418.html',1,'std::__debug::unordered_multiset&lt; typename _Value, typename _Hash, typename _Pred, typename _Alloc &gt;'],['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a07550.html',1,'std::unordered_multiset&lt; typename _Value, typename _Hash, typename _Pred, typename _Alloc &gt;']]],
  ['unordered_5fset_30',['unordered_set',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a08414.html',1,'std::__debug::unordered_set&lt; typename _Value, typename _Hash, typename _Pred, typename _Alloc &gt;'],['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a07554.html',1,'std::unordered_set&lt; typename _Value, typename _Hash, typename _Pred, typename _Alloc &gt;']]],
  ['unsynchronized_5fpool_5fresource_31',['unsynchronized_pool_resource',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a02798.html',1,'std::pmr']]],
  ['uses_5fallocator_32',['uses_allocator',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a05150.html',1,'std']]],
  ['uses_5fallocator_3c_20tuple_3c_20_5ftypes_2e_2e_2e_20_3e_2c_20_5falloc_20_3e_33',['uses_allocator&lt; tuple&lt; _Types... &gt;, _Alloc &gt;',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a03058.html',1,'std']]],
  ['utc_5fclock_34',['utc_clock',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a02086.html',1,'std::chrono']]],
  ['utilities_35',['Utilities',['../../../samrai/2.4.4/html/structSAMRAI_1_1tbox_1_1Utilities.html',1,'SAMRAI::tbox']]]
];
