var searchData=
[
  ['unary_5fcompose_11350',['unary_compose',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a09559.html',1,'__gnu_cxx']]],
  ['unary_5ffunction_11351',['unary_function',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a07883.html',1,'std']]],
  ['unary_5ffunction_3c_20_5f_5fgnu_5fcxx_3a_3athrow_5fvalue_5flimit_2c_20size_5ft_20_3e_11352',['unary_function&lt; __gnu_cxx::throw_value_limit, size_t &gt;',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a07883.html',1,'std']]],
  ['unary_5ffunction_3c_20_5f_5fgnu_5fcxx_3a_3athrow_5fvalue_5frandom_2c_20size_5ft_20_3e_11353',['unary_function&lt; __gnu_cxx::throw_value_random, size_t &gt;',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a07883.html',1,'std']]],
  ['unary_5ffunction_3c_20_5foperation_3a_3afirst_5fargument_5ftype_2c_20_5foperation_3a_3aresult_5ftype_20_3e_11354',['unary_function&lt; _Operation::first_argument_type, _Operation::result_type &gt;',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a07883.html',1,'std']]],
  ['unary_5ffunction_3c_20_5foperation_3a_3asecond_5fargument_5ftype_2c_20_5foperation_3a_3aresult_5ftype_20_3e_11355',['unary_function&lt; _Operation::second_argument_type, _Operation::result_type &gt;',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a07883.html',1,'std']]],
  ['unary_5ffunction_3c_20_5fpredicate_3a_3aargument_5ftype_2c_20bool_20_3e_11356',['unary_function&lt; _Predicate::argument_type, bool &gt;',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a07883.html',1,'std']]],
  ['unary_5ffunction_3c_20_5ftp_20_2a_2c_20_5fret_20_3e_11357',['unary_function&lt; _Tp *, _Ret &gt;',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a07883.html',1,'std']]],
  ['unary_5ffunction_3c_20_5ftp_2c_20_5fret_20_3e_11358',['unary_function&lt; _Tp, _Ret &gt;',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a07883.html',1,'std']]],
  ['unary_5ffunction_3c_20_5ftp_2c_20_5ftp_20_3e_11359',['unary_function&lt; _Tp, _Tp &gt;',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a07883.html',1,'std']]],
  ['unary_5ffunction_3c_20_5ftp_2c_20bool_20_3e_11360',['unary_function&lt; _Tp, bool &gt;',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a07883.html',1,'std']]],
  ['unary_5ffunction_3c_20const_20_5ftp_20_2a_2c_20_5fret_20_3e_11361',['unary_function&lt; const _Tp *, _Ret &gt;',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a07883.html',1,'std']]],
  ['unary_5fnegate_11362',['unary_negate',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a08123.html',1,'std']]],
  ['unbalanced_5ftag_11363',['unbalanced_tag',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a10119.html',1,'__gnu_parallel']]],
  ['underflow_5ferror_11364',['underflow_error',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a03363.html',1,'std']]],
  ['underlying_5ftype_11365',['underlying_type',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a04283.html',1,'std']]],
  ['uniform_5fint_5fdistribution_11366',['uniform_int_distribution',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a08575.html',1,'std']]],
  ['uniform_5freal_5fdistribution_11367',['uniform_real_distribution',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a06515.html',1,'std']]],
  ['unique_5flock_11368',['unique_lock',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a08583.html',1,'std']]],
  ['unique_5fptr_11369',['unique_ptr',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a08595.html',1,'std']]],
  ['unique_5fptr_3c_20_5ftp_5b_5d_2c_20_5fdp_20_3e_11370',['unique_ptr&lt; _Tp[], _Dp &gt;',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a08599.html',1,'std']]],
  ['unique_5fptr_3c_20samrai_3a_3amesh_3a_3astandardtagandinitstrategy_3c_20ndim_20_3e_20_3e_11371',['unique_ptr&lt; SAMRAI::mesh::StandardTagAndInitStrategy&lt; NDIM &gt; &gt;',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a08595.html',1,'std']]],
  ['unique_5fptr_3c_20samrai_3a_3asolv_3a_3apoissonspecifications_20_3e_11372',['unique_ptr&lt; SAMRAI::solv::PoissonSpecifications &gt;',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a08595.html',1,'std']]],
  ['unique_5fptr_3c_20samrai_3a_3asolv_3a_3arobinbccoefstrategy_3c_20ndim_20_3e_20_3e_11373',['unique_ptr&lt; SAMRAI::solv::RobinBcCoefStrategy&lt; NDIM &gt; &gt;',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a08595.html',1,'std']]],
  ['unique_5fptr_3c_20samrai_3a_3axfer_3a_3acoarsenpatchstrategy_3c_20ndim_20_3e_20_3e_11374',['unique_ptr&lt; SAMRAI::xfer::CoarsenPatchStrategy&lt; NDIM &gt; &gt;',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a08595.html',1,'std']]],
  ['unique_5fptr_3c_20samrai_3a_3axfer_3a_3arefinepatchstrategy_3c_20ndim_20_3e_20_3e_11375',['unique_ptr&lt; SAMRAI::xfer::RefinePatchStrategy&lt; NDIM &gt; &gt;',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a08595.html',1,'std']]],
  ['unique_5fptr_3c_20std_3a_3abasic_5fofstream_20_3e_11376',['unique_ptr&lt; std::basic_ofstream &gt;',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a08595.html',1,'std']]],
  ['unordered_5fmap_11377',['unordered_map',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a09495.html',1,'std::__debug::unordered_map&lt; typename _Key, typename _Tp, typename _Hash, typename _Pred, typename _Alloc &gt;'],['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a08615.html',1,'std::unordered_map&lt; typename _Key, typename _Tp, typename _Hash, typename _Pred, typename _Alloc &gt;']]],
  ['unordered_5fmultimap_11378',['unordered_multimap',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a09499.html',1,'std::__debug::unordered_multimap&lt; typename _Key, typename _Tp, typename _Hash, typename _Pred, typename _Alloc &gt;'],['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a08611.html',1,'std::unordered_multimap&lt; typename _Key, typename _Tp, typename _Hash, typename _Pred, typename _Alloc &gt;']]],
  ['unordered_5fmultiset_11379',['unordered_multiset',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a09515.html',1,'std::__debug::unordered_multiset&lt; typename _Value, typename _Hash, typename _Pred, typename _Alloc &gt;'],['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a08627.html',1,'std::unordered_multiset&lt; typename _Value, typename _Hash, typename _Pred, typename _Alloc &gt;']]],
  ['unordered_5fset_11380',['unordered_set',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a09511.html',1,'std::__debug::unordered_set&lt; typename _Value, typename _Hash, typename _Pred, typename _Alloc &gt;'],['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a08631.html',1,'std::unordered_set&lt; typename _Value, typename _Hash, typename _Pred, typename _Alloc &gt;']]],
  ['unsynchronized_5fpool_5fresource_11381',['unsynchronized_pool_resource',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a02787.html',1,'std::pmr']]],
  ['unwrap_5fref_5fdecay_11382',['unwrap_ref_decay',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a04363.html',1,'std']]],
  ['unwrap_5freference_11383',['unwrap_reference',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a04355.html',1,'std']]],
  ['uses_5fallocator_11384',['uses_allocator',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a06175.html',1,'std']]],
  ['uses_5fallocator_3c_20tuple_3c_20_5ftypes_2e_2e_2e_20_3e_2c_20_5falloc_20_3e_11385',['uses_allocator&lt; tuple&lt; _Types... &gt;, _Alloc &gt;',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a03631.html',1,'std']]],
  ['utilities_11386',['Utilities',['../../../samrai/2.4.4/html/structSAMRAI_1_1tbox_1_1Utilities.html',1,'SAMRAI::tbox']]]
];
