var searchData=
[
  ['packaged_5ftask_3c_20_5fres_28_5fargtypes_2e_2e_2e_29_3e_10764',['packaged_task&lt; _Res(_ArgTypes...)&gt;',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a02583.html',1,'std']]],
  ['pair_10765',['pair',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a08303.html',1,'std']]],
  ['pair_3c_20_5fraiter_2c_20_5fraiter_20_3e_10766',['pair&lt; _RAIter, _RAIter &gt;',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a08303.html',1,'std']]],
  ['pair_3c_20int_2c_20int_20_3e_10767',['pair&lt; int, int &gt;',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a08303.html',1,'std']]],
  ['pair_3c_20point_2c_20point_20_3e_10768',['pair&lt; Point, Point &gt;',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a08303.html',1,'std']]],
  ['pairing_5fheap_10769',['pairing_heap',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a13243.html',1,'__gnu_pbds::detail']]],
  ['pairing_5fheap_5ftag_10770',['pairing_heap_tag',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a12679.html',1,'__gnu_pbds']]],
  ['parallel_5ftag_10771',['parallel_tag',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a10107.html',1,'__gnu_parallel']]],
  ['parallelbuffer_10772',['ParallelBuffer',['../../../samrai/2.4.4/html/classSAMRAI_1_1tbox_1_1ParallelBuffer.html',1,'SAMRAI::tbox']]],
  ['paralleledgemap_10773',['ParallelEdgeMap',['../class_i_b_t_k_1_1_parallel_edge_map.html',1,'IBTK']]],
  ['parallelmap_10774',['ParallelMap',['../class_i_b_t_k_1_1_parallel_map.html',1,'IBTK']]],
  ['parallelset_10775',['ParallelSet',['../class_i_b_t_k_1_1_parallel_set.html',1,'IBTK']]],
  ['param_5ftype_10776',['param_type',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a06583.html',1,'std::bernoulli_distribution::param_type'],['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a06591.html',1,'std::binomial_distribution&lt; typename _IntType &gt;::param_type'],['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a06559.html',1,'std::cauchy_distribution&lt; typename _RealType &gt;::param_type'],['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a06551.html',1,'std::chi_squared_distribution&lt; typename _RealType &gt;::param_type'],['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a06647.html',1,'std::discrete_distribution&lt; typename _IntType &gt;::param_type'],['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a06623.html',1,'std::exponential_distribution&lt; typename _RealType &gt;::param_type'],['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a06639.html',1,'std::extreme_value_distribution&lt; typename _RealType &gt;::param_type'],['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a06567.html',1,'std::fisher_f_distribution&lt; typename _RealType &gt;::param_type'],['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a06543.html',1,'std::gamma_distribution&lt; typename _RealType &gt;::param_type'],['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a06599.html',1,'std::geometric_distribution&lt; typename _IntType &gt;::param_type'],['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a06535.html',1,'std::lognormal_distribution&lt; typename _RealType &gt;::param_type'],['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a06607.html',1,'std::negative_binomial_distribution&lt; typename _IntType &gt;::param_type'],['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a06527.html',1,'std::normal_distribution&lt; typename _RealType &gt;::param_type'],['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a06655.html',1,'std::piecewise_constant_distribution::param_type'],['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a06663.html',1,'std::piecewise_linear_distribution::param_type'],['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a06615.html',1,'std::poisson_distribution::param_type'],['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a06575.html',1,'std::student_t_distribution::param_type'],['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a08579.html',1,'std::uniform_int_distribution::param_type'],['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a06519.html',1,'std::uniform_real_distribution::param_type'],['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a06631.html',1,'std::weibull_distribution::param_type']]],
  ['parser_10777',['Parser',['../../../samrai/2.4.4/html/classSAMRAI_1_1tbox_1_1Parser.html',1,'SAMRAI::tbox']]],
  ['partitioningbox_10778',['PartitioningBox',['../class_i_b_t_k_1_1_partitioning_box.html',1,'IBTK']]],
  ['partitioningboxes_10779',['PartitioningBoxes',['../class_i_b_t_k_1_1_partitioning_boxes.html',1,'IBTK']]],
  ['pat_5ftrie_5fbase_10780',['pat_trie_base',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a13259.html',1,'__gnu_pbds::detail']]],
  ['pat_5ftrie_5fmap_10781',['pat_trie_map',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a13247.html',1,'__gnu_pbds::detail']]],
  ['pat_5ftrie_5ftag_10782',['pat_trie_tag',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a12667.html',1,'__gnu_pbds']]],
  ['patch_10783',['Patch',['../../../samrai/2.4.4/html/classSAMRAI_1_1hier_1_1Patch.html',1,'SAMRAI::hier']]],
  ['patchboundaryedgesum_10784',['PatchBoundaryEdgeSum',['../../../samrai/2.4.4/html/classSAMRAI_1_1algs_1_1PatchBoundaryEdgeSum.html',1,'SAMRAI::algs']]],
  ['patchboundarynodesum_10785',['PatchBoundaryNodeSum',['../../../samrai/2.4.4/html/classSAMRAI_1_1algs_1_1PatchBoundaryNodeSum.html',1,'SAMRAI::algs']]],
  ['patchcelldatabasicops_10786',['PatchCellDataBasicOps',['../../../samrai/2.4.4/html/classSAMRAI_1_1math_1_1PatchCellDataBasicOps.html',1,'SAMRAI::math']]],
  ['patchcelldatabasicops_3c_20dim_2c_20int_20_3e_10787',['PatchCellDataBasicOps&lt; DIM, int &gt;',['../../../samrai/2.4.4/html/classSAMRAI_1_1math_1_1PatchCellDataBasicOps.html',1,'SAMRAI::math']]],
  ['patchcelldatamiscellaneousopsreal_10788',['PatchCellDataMiscellaneousOpsReal',['../../../samrai/2.4.4/html/classSAMRAI_1_1math_1_1PatchCellDataMiscellaneousOpsReal.html',1,'SAMRAI::math']]],
  ['patchcelldatanormopscomplex_10789',['PatchCellDataNormOpsComplex',['../../../samrai/2.4.4/html/classSAMRAI_1_1math_1_1PatchCellDataNormOpsComplex.html',1,'SAMRAI::math']]],
  ['patchcelldatanormopsreal_10790',['PatchCellDataNormOpsReal',['../../../samrai/2.4.4/html/classSAMRAI_1_1math_1_1PatchCellDataNormOpsReal.html',1,'SAMRAI::math']]],
  ['patchcelldataopscomplex_10791',['PatchCellDataOpsComplex',['../../../samrai/2.4.4/html/classSAMRAI_1_1math_1_1PatchCellDataOpsComplex.html',1,'SAMRAI::math']]],
  ['patchcelldataopsinteger_10792',['PatchCellDataOpsInteger',['../../../samrai/2.4.4/html/classSAMRAI_1_1math_1_1PatchCellDataOpsInteger.html',1,'SAMRAI::math']]],
  ['patchcelldataopsreal_10793',['PatchCellDataOpsReal',['../../../samrai/2.4.4/html/classSAMRAI_1_1math_1_1PatchCellDataOpsReal.html',1,'SAMRAI::math']]],
  ['patchconfigurationutilities_10794',['PatchConfigurationUtilities',['../../../samrai/2.4.4/html/classSAMRAI_1_1hier_1_1PatchConfigurationUtilities.html',1,'SAMRAI::hier']]],
  ['patchdata_10795',['PatchData',['../../../samrai/2.4.4/html/classSAMRAI_1_1hier_1_1PatchData.html',1,'SAMRAI::hier']]],
  ['patchdatafactory_10796',['PatchDataFactory',['../../../samrai/2.4.4/html/classSAMRAI_1_1hier_1_1PatchDataFactory.html',1,'SAMRAI::hier']]],
  ['patchdataid_10797',['PatchDataId',['../../../samrai/2.4.4/html/structSAMRAI_1_1hier_1_1PatchDataId.html',1,'SAMRAI::hier']]],
  ['patchdescriptor_10798',['PatchDescriptor',['../../../samrai/2.4.4/html/classSAMRAI_1_1hier_1_1PatchDescriptor.html',1,'SAMRAI::hier']]],
  ['patchedgedatabasicops_10799',['PatchEdgeDataBasicOps',['../../../samrai/2.4.4/html/classSAMRAI_1_1math_1_1PatchEdgeDataBasicOps.html',1,'SAMRAI::math']]],
  ['patchedgedatabasicops_3c_20dim_2c_20int_20_3e_10800',['PatchEdgeDataBasicOps&lt; DIM, int &gt;',['../../../samrai/2.4.4/html/classSAMRAI_1_1math_1_1PatchEdgeDataBasicOps.html',1,'SAMRAI::math']]],
  ['patchedgedatamiscellaneousopsreal_10801',['PatchEdgeDataMiscellaneousOpsReal',['../../../samrai/2.4.4/html/classSAMRAI_1_1math_1_1PatchEdgeDataMiscellaneousOpsReal.html',1,'SAMRAI::math']]],
  ['patchedgedatanormopscomplex_10802',['PatchEdgeDataNormOpsComplex',['../../../samrai/2.4.4/html/classSAMRAI_1_1math_1_1PatchEdgeDataNormOpsComplex.html',1,'SAMRAI::math']]],
  ['patchedgedatanormopsreal_10803',['PatchEdgeDataNormOpsReal',['../../../samrai/2.4.4/html/classSAMRAI_1_1math_1_1PatchEdgeDataNormOpsReal.html',1,'SAMRAI::math']]],
  ['patchedgedataopscomplex_10804',['PatchEdgeDataOpsComplex',['../../../samrai/2.4.4/html/classSAMRAI_1_1math_1_1PatchEdgeDataOpsComplex.html',1,'SAMRAI::math']]],
  ['patchedgedataopsinteger_10805',['PatchEdgeDataOpsInteger',['../../../samrai/2.4.4/html/classSAMRAI_1_1math_1_1PatchEdgeDataOpsInteger.html',1,'SAMRAI::math']]],
  ['patchedgedataopsreal_10806',['PatchEdgeDataOpsReal',['../../../samrai/2.4.4/html/classSAMRAI_1_1math_1_1PatchEdgeDataOpsReal.html',1,'SAMRAI::math']]],
  ['patchfacedatabasicops_10807',['PatchFaceDataBasicOps',['../../../samrai/2.4.4/html/classSAMRAI_1_1math_1_1PatchFaceDataBasicOps.html',1,'SAMRAI::math']]],
  ['patchfacedatabasicops_3c_20dim_2c_20int_20_3e_10808',['PatchFaceDataBasicOps&lt; DIM, int &gt;',['../../../samrai/2.4.4/html/classSAMRAI_1_1math_1_1PatchFaceDataBasicOps.html',1,'SAMRAI::math']]],
  ['patchfacedatamiscellaneousopsreal_10809',['PatchFaceDataMiscellaneousOpsReal',['../../../samrai/2.4.4/html/classSAMRAI_1_1math_1_1PatchFaceDataMiscellaneousOpsReal.html',1,'SAMRAI::math']]],
  ['patchfacedatanormopscomplex_10810',['PatchFaceDataNormOpsComplex',['../../../samrai/2.4.4/html/classSAMRAI_1_1math_1_1PatchFaceDataNormOpsComplex.html',1,'SAMRAI::math']]],
  ['patchfacedatanormopsreal_10811',['PatchFaceDataNormOpsReal',['../../../samrai/2.4.4/html/classSAMRAI_1_1math_1_1PatchFaceDataNormOpsReal.html',1,'SAMRAI::math']]],
  ['patchfacedataopscomplex_10812',['PatchFaceDataOpsComplex',['../../../samrai/2.4.4/html/classSAMRAI_1_1math_1_1PatchFaceDataOpsComplex.html',1,'SAMRAI::math']]],
  ['patchfacedataopsinteger_10813',['PatchFaceDataOpsInteger',['../../../samrai/2.4.4/html/classSAMRAI_1_1math_1_1PatchFaceDataOpsInteger.html',1,'SAMRAI::math']]],
  ['patchfacedataopsreal_10814',['PatchFaceDataOpsReal',['../../../samrai/2.4.4/html/classSAMRAI_1_1math_1_1PatchFaceDataOpsReal.html',1,'SAMRAI::math']]],
  ['patchfactory_10815',['PatchFactory',['../../../samrai/2.4.4/html/classSAMRAI_1_1hier_1_1PatchFactory.html',1,'SAMRAI::hier']]],
  ['patchgeometry_10816',['PatchGeometry',['../../../samrai/2.4.4/html/classSAMRAI_1_1hier_1_1PatchGeometry.html',1,'SAMRAI::hier']]],
  ['patchhierarchy_10817',['PatchHierarchy',['../../../samrai/2.4.4/html/classSAMRAI_1_1hier_1_1PatchHierarchy.html',1,'SAMRAI::hier']]],
  ['patchlevel_10818',['PatchLevel',['../../../samrai/2.4.4/html/classSAMRAI_1_1hier_1_1PatchLevel.html',1,'SAMRAI::hier']]],
  ['patchlevelfactory_10819',['PatchLevelFactory',['../../../samrai/2.4.4/html/classSAMRAI_1_1hier_1_1PatchLevelFactory.html',1,'SAMRAI::hier']]],
  ['patchleveliterator_10820',['PatchLevelIterator',['../../../samrai/2.4.4/html/classSAMRAI_1_1hier_1_1PatchLevelIterator.html',1,'SAMRAI::hier']]],
  ['patchmathops_10821',['PatchMathOps',['../class_i_b_t_k_1_1_patch_math_ops.html',1,'IBTK']]],
  ['patchnodedatabasicops_10822',['PatchNodeDataBasicOps',['../../../samrai/2.4.4/html/classSAMRAI_1_1math_1_1PatchNodeDataBasicOps.html',1,'SAMRAI::math']]],
  ['patchnodedatabasicops_3c_20dim_2c_20int_20_3e_10823',['PatchNodeDataBasicOps&lt; DIM, int &gt;',['../../../samrai/2.4.4/html/classSAMRAI_1_1math_1_1PatchNodeDataBasicOps.html',1,'SAMRAI::math']]],
  ['patchnodedatamiscellaneousopsreal_10824',['PatchNodeDataMiscellaneousOpsReal',['../../../samrai/2.4.4/html/classSAMRAI_1_1math_1_1PatchNodeDataMiscellaneousOpsReal.html',1,'SAMRAI::math']]],
  ['patchnodedatanormopscomplex_10825',['PatchNodeDataNormOpsComplex',['../../../samrai/2.4.4/html/classSAMRAI_1_1math_1_1PatchNodeDataNormOpsComplex.html',1,'SAMRAI::math']]],
  ['patchnodedatanormopsreal_10826',['PatchNodeDataNormOpsReal',['../../../samrai/2.4.4/html/classSAMRAI_1_1math_1_1PatchNodeDataNormOpsReal.html',1,'SAMRAI::math']]],
  ['patchnodedataopscomplex_10827',['PatchNodeDataOpsComplex',['../../../samrai/2.4.4/html/classSAMRAI_1_1math_1_1PatchNodeDataOpsComplex.html',1,'SAMRAI::math']]],
  ['patchnodedataopsinteger_10828',['PatchNodeDataOpsInteger',['../../../samrai/2.4.4/html/classSAMRAI_1_1math_1_1PatchNodeDataOpsInteger.html',1,'SAMRAI::math']]],
  ['patchnodedataopsreal_10829',['PatchNodeDataOpsReal',['../../../samrai/2.4.4/html/classSAMRAI_1_1math_1_1PatchNodeDataOpsReal.html',1,'SAMRAI::math']]],
  ['patchnumber_10830',['PatchNumber',['../../../samrai/2.4.4/html/structSAMRAI_1_1hier_1_1PatchNumber.html',1,'SAMRAI::hier']]],
  ['patchsidedatabasicops_10831',['PatchSideDataBasicOps',['../../../samrai/2.4.4/html/classSAMRAI_1_1math_1_1PatchSideDataBasicOps.html',1,'SAMRAI::math']]],
  ['patchsidedatabasicops_3c_20dim_2c_20int_20_3e_10832',['PatchSideDataBasicOps&lt; DIM, int &gt;',['../../../samrai/2.4.4/html/classSAMRAI_1_1math_1_1PatchSideDataBasicOps.html',1,'SAMRAI::math']]],
  ['patchsidedatamiscellaneousopsreal_10833',['PatchSideDataMiscellaneousOpsReal',['../../../samrai/2.4.4/html/classSAMRAI_1_1math_1_1PatchSideDataMiscellaneousOpsReal.html',1,'SAMRAI::math']]],
  ['patchsidedatanormopscomplex_10834',['PatchSideDataNormOpsComplex',['../../../samrai/2.4.4/html/classSAMRAI_1_1math_1_1PatchSideDataNormOpsComplex.html',1,'SAMRAI::math']]],
  ['patchsidedatanormopsreal_10835',['PatchSideDataNormOpsReal',['../../../samrai/2.4.4/html/classSAMRAI_1_1math_1_1PatchSideDataNormOpsReal.html',1,'SAMRAI::math']]],
  ['patchsidedataopscomplex_10836',['PatchSideDataOpsComplex',['../../../samrai/2.4.4/html/classSAMRAI_1_1math_1_1PatchSideDataOpsComplex.html',1,'SAMRAI::math']]],
  ['patchsidedataopsinteger_10837',['PatchSideDataOpsInteger',['../../../samrai/2.4.4/html/classSAMRAI_1_1math_1_1PatchSideDataOpsInteger.html',1,'SAMRAI::math']]],
  ['patchsidedataopsreal_10838',['PatchSideDataOpsReal',['../../../samrai/2.4.4/html/classSAMRAI_1_1math_1_1PatchSideDataOpsReal.html',1,'SAMRAI::math']]],
  ['patchstat_10839',['PatchStat',['../../../samrai/2.4.4/html/structSAMRAI_1_1tbox_1_1Statistic_1_1PatchStat.html',1,'SAMRAI::tbox::Statistic']]],
  ['patchstatrecord_10840',['PatchStatRecord',['../../../samrai/2.4.4/html/structSAMRAI_1_1tbox_1_1Statistic_1_1PatchStatRecord.html',1,'SAMRAI::tbox::Statistic']]],
  ['path_10841',['path',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a10259.html',1,'std::experimental::filesystem::v1::path'],['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a05675.html',1,'std::filesystem::path']]],
  ['penaltyibmethod_10842',['PenaltyIBMethod',['../class_i_b_a_m_r_1_1_penalty_i_b_method.html',1,'IBAMR']]],
  ['petsc_5fsamraivectorreal_10843',['PETSc_SAMRAIVectorReal',['../../../samrai/2.4.4/html/classSAMRAI_1_1solv_1_1PETSc__SAMRAIVectorReal.html',1,'SAMRAI::solv']]],
  ['petscabstractvectorreal_10844',['PETScAbstractVectorReal',['../../../samrai/2.4.4/html/classSAMRAI_1_1solv_1_1PETScAbstractVectorReal.html',1,'SAMRAI::solv']]],
  ['petsckrylovlinearsolver_10845',['PETScKrylovLinearSolver',['../class_i_b_t_k_1_1_p_e_t_sc_krylov_linear_solver.html',1,'IBTK']]],
  ['petsckrylovpoissonsolver_10846',['PETScKrylovPoissonSolver',['../class_i_b_t_k_1_1_p_e_t_sc_krylov_poisson_solver.html',1,'IBTK']]],
  ['petsckrylovstaggeredstokessolver_10847',['PETScKrylovStaggeredStokesSolver',['../class_i_b_a_m_r_1_1_p_e_t_sc_krylov_staggered_stokes_solver.html',1,'IBAMR']]],
  ['petsclevelsolver_10848',['PETScLevelSolver',['../class_i_b_t_k_1_1_p_e_t_sc_level_solver.html',1,'IBTK']]],
  ['petscmatlowrapper_10849',['PETScMatLOWrapper',['../class_i_b_t_k_1_1_p_e_t_sc_mat_l_o_wrapper.html',1,'IBTK']]],
  ['petscmatutilities_10850',['PETScMatUtilities',['../class_i_b_t_k_1_1_p_e_t_sc_mat_utilities.html',1,'IBTK']]],
  ['petscmffdjacobianoperator_10851',['PETScMFFDJacobianOperator',['../class_i_b_t_k_1_1_p_e_t_sc_m_f_f_d_jacobian_operator.html',1,'IBTK']]],
  ['petscnewtonkrylovsolver_10852',['PETScNewtonKrylovSolver',['../class_i_b_t_k_1_1_p_e_t_sc_newton_krylov_solver.html',1,'IBTK']]],
  ['petscpclswrapper_10853',['PETScPCLSWrapper',['../class_i_b_t_k_1_1_p_e_t_sc_p_c_l_s_wrapper.html',1,'IBTK']]],
  ['petscsamraivectorreal_10854',['PETScSAMRAIVectorReal',['../class_i_b_t_k_1_1_p_e_t_sc_s_a_m_r_a_i_vector_real.html',1,'IBTK']]],
  ['petscsnesfunctiongowrapper_10855',['PETScSNESFunctionGOWrapper',['../class_i_b_t_k_1_1_p_e_t_sc_s_n_e_s_function_g_o_wrapper.html',1,'IBTK']]],
  ['petscsnesjacobianjowrapper_10856',['PETScSNESJacobianJOWrapper',['../class_i_b_t_k_1_1_p_e_t_sc_s_n_e_s_jacobian_j_o_wrapper.html',1,'IBTK']]],
  ['petscvecutilities_10857',['PETScVecUtilities',['../class_i_b_t_k_1_1_p_e_t_sc_vec_utilities.html',1,'IBTK']]],
  ['phasechangedivusourcefunction_10858',['PhaseChangeDivUSourceFunction',['../class_i_b_a_m_r_1_1_phase_change_div_u_source_function.html',1,'IBAMR']]],
  ['physicalboundaryutilities_10859',['PhysicalBoundaryUtilities',['../class_i_b_t_k_1_1_physical_boundary_utilities.html',1,'IBTK']]],
  ['piecewise_5fconstant_5fdistribution_10860',['piecewise_constant_distribution',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a06651.html',1,'std']]],
  ['piecewise_5fconstruct_5ft_10861',['piecewise_construct_t',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a08427.html',1,'std']]],
  ['piecewise_5flinear_5fdistribution_10862',['piecewise_linear_distribution',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a06659.html',1,'std']]],
  ['pio_10863',['PIO',['../../../samrai/2.4.4/html/structSAMRAI_1_1tbox_1_1PIO.html',1,'SAMRAI::tbox']]],
  ['plus_10864',['plus',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a07891.html',1,'std']]],
  ['point_5finvalidation_5fguarantee_10865',['point_invalidation_guarantee',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a12607.html',1,'__gnu_pbds']]],
  ['pointer_10866',['Pointer',['../../../samrai/2.4.4/html/classSAMRAI_1_1tbox_1_1Pointer.html',1,'SAMRAI::tbox']]],
  ['pointer_3c_20ibamr_3a_3aadvdiffhierarchyintegrator_20_3e_10867',['Pointer&lt; IBAMR::AdvDiffHierarchyIntegrator &gt;',['../../../samrai/2.4.4/html/classSAMRAI_1_1tbox_1_1Pointer.html',1,'SAMRAI::tbox']]],
  ['pointer_3c_20ibamr_3a_3aadvdiffpredictorcorrectorhyperbolicpatchops_20_3e_10868',['Pointer&lt; IBAMR::AdvDiffPredictorCorrectorHyperbolicPatchOps &gt;',['../../../samrai/2.4.4/html/classSAMRAI_1_1tbox_1_1Pointer.html',1,'SAMRAI::tbox']]],
  ['pointer_3c_20ibamr_3a_3aadvdiffsemiimplicithierarchyintegrator_20_3e_10869',['Pointer&lt; IBAMR::AdvDiffSemiImplicitHierarchyIntegrator &gt;',['../../../samrai/2.4.4/html/classSAMRAI_1_1tbox_1_1Pointer.html',1,'SAMRAI::tbox']]],
  ['pointer_3c_20ibamr_3a_3aadvectorexplicitpredictorpatchops_20_3e_10870',['Pointer&lt; IBAMR::AdvectorExplicitPredictorPatchOps &gt;',['../../../samrai/2.4.4/html/classSAMRAI_1_1tbox_1_1Pointer.html',1,'SAMRAI::tbox']]],
  ['pointer_3c_20ibamr_3a_3abrinkmanadvdiffbchelper_20_3e_10871',['Pointer&lt; IBAMR::BrinkmanAdvDiffBcHelper &gt;',['../../../samrai/2.4.4/html/classSAMRAI_1_1tbox_1_1Pointer.html',1,'SAMRAI::tbox']]],
  ['pointer_3c_20ibamr_3a_3acellconvectiveoperator_20_3e_10872',['Pointer&lt; IBAMR::CellConvectiveOperator &gt;',['../../../samrai/2.4.4/html/classSAMRAI_1_1tbox_1_1Pointer.html',1,'SAMRAI::tbox']]],
  ['pointer_3c_20ibamr_3a_3acfstrategy_20_3e_10873',['Pointer&lt; IBAMR::CFStrategy &gt;',['../../../samrai/2.4.4/html/classSAMRAI_1_1tbox_1_1Pointer.html',1,'SAMRAI::tbox']]],
  ['pointer_3c_20ibamr_3a_3acfupperconvectiveoperator_20_3e_10874',['Pointer&lt; IBAMR::CFUpperConvectiveOperator &gt;',['../../../samrai/2.4.4/html/classSAMRAI_1_1tbox_1_1Pointer.html',1,'SAMRAI::tbox']]],
  ['pointer_3c_20ibamr_3a_3acibmobilitysolver_20_3e_10875',['Pointer&lt; IBAMR::CIBMobilitySolver &gt;',['../../../samrai/2.4.4/html/classSAMRAI_1_1tbox_1_1Pointer.html',1,'SAMRAI::tbox']]],
  ['pointer_3c_20ibamr_3a_3acibsaddlepointsolver_20_3e_10876',['Pointer&lt; IBAMR::CIBSaddlePointSolver &gt;',['../../../samrai/2.4.4/html/classSAMRAI_1_1tbox_1_1Pointer.html',1,'SAMRAI::tbox']]],
  ['pointer_3c_20ibamr_3a_3acibstaggeredstokesoperator_20_3e_10877',['Pointer&lt; IBAMR::CIBStaggeredStokesOperator &gt;',['../../../samrai/2.4.4/html/classSAMRAI_1_1tbox_1_1Pointer.html',1,'SAMRAI::tbox']]],
  ['pointer_3c_20ibamr_3a_3acibstrategy_20_3e_10878',['Pointer&lt; IBAMR::CIBStrategy &gt;',['../../../samrai/2.4.4/html/classSAMRAI_1_1tbox_1_1Pointer.html',1,'SAMRAI::tbox']]],
  ['pointer_3c_20ibamr_3a_3aconvectiveoperator_20_3e_10879',['Pointer&lt; IBAMR::ConvectiveOperator &gt;',['../../../samrai/2.4.4/html/classSAMRAI_1_1tbox_1_1Pointer.html',1,'SAMRAI::tbox']]],
  ['pointer_3c_20ibamr_3a_3adirectmobilitysolver_20_3e_10880',['Pointer&lt; IBAMR::DirectMobilitySolver &gt;',['../../../samrai/2.4.4/html/classSAMRAI_1_1tbox_1_1Pointer.html',1,'SAMRAI::tbox']]],
  ['pointer_3c_20ibamr_3a_3aibfemethod_20_3e_10881',['Pointer&lt; IBAMR::IBFEMethod &gt;',['../../../samrai/2.4.4/html/classSAMRAI_1_1tbox_1_1Pointer.html',1,'SAMRAI::tbox']]],
  ['pointer_3c_20ibamr_3a_3aibimplicitstrategy_20_3e_10882',['Pointer&lt; IBAMR::IBImplicitStrategy &gt;',['../../../samrai/2.4.4/html/classSAMRAI_1_1tbox_1_1Pointer.html',1,'SAMRAI::tbox']]],
  ['pointer_3c_20ibamr_3a_3aibinstrumentpanel_20_3e_10883',['Pointer&lt; IBAMR::IBInstrumentPanel &gt;',['../../../samrai/2.4.4/html/classSAMRAI_1_1tbox_1_1Pointer.html',1,'SAMRAI::tbox']]],
  ['pointer_3c_20ibamr_3a_3aibinterpolantmethod_20_3e_10884',['Pointer&lt; IBAMR::IBInterpolantMethod &gt;',['../../../samrai/2.4.4/html/classSAMRAI_1_1tbox_1_1Pointer.html',1,'SAMRAI::tbox']]],
  ['pointer_3c_20ibamr_3a_3aibkirchhoffrodforcegen_20_3e_10885',['Pointer&lt; IBAMR::IBKirchhoffRodForceGen &gt;',['../../../samrai/2.4.4/html/classSAMRAI_1_1tbox_1_1Pointer.html',1,'SAMRAI::tbox']]],
  ['pointer_3c_20ibamr_3a_3aiblagrangianforcestrategy_20_3e_10886',['Pointer&lt; IBAMR::IBLagrangianForceStrategy &gt;',['../../../samrai/2.4.4/html/classSAMRAI_1_1tbox_1_1Pointer.html',1,'SAMRAI::tbox']]],
  ['pointer_3c_20ibamr_3a_3aiblagrangiansourcestrategy_20_3e_10887',['Pointer&lt; IBAMR::IBLagrangianSourceStrategy &gt;',['../../../samrai/2.4.4/html/classSAMRAI_1_1tbox_1_1Pointer.html',1,'SAMRAI::tbox']]],
  ['pointer_3c_20ibamr_3a_3aiblevelsetmethod_20_3e_10888',['Pointer&lt; IBAMR::IBLevelSetMethod &gt;',['../../../samrai/2.4.4/html/classSAMRAI_1_1tbox_1_1Pointer.html',1,'SAMRAI::tbox']]],
  ['pointer_3c_20ibamr_3a_3aibmethodpostprocessstrategy_20_3e_10889',['Pointer&lt; IBAMR::IBMethodPostProcessStrategy &gt;',['../../../samrai/2.4.4/html/classSAMRAI_1_1tbox_1_1Pointer.html',1,'SAMRAI::tbox']]],
  ['pointer_3c_20ibamr_3a_3aibstrategy_20_3e_10890',['Pointer&lt; IBAMR::IBStrategy &gt;',['../../../samrai/2.4.4/html/classSAMRAI_1_1tbox_1_1Pointer.html',1,'SAMRAI::tbox']]],
  ['pointer_3c_20ibamr_3a_3ainshierarchyintegrator_20_3e_10891',['Pointer&lt; IBAMR::INSHierarchyIntegrator &gt;',['../../../samrai/2.4.4/html/classSAMRAI_1_1tbox_1_1Pointer.html',1,'SAMRAI::tbox']]],
  ['pointer_3c_20ibamr_3a_3ainsstaggeredhierarchyintegrator_20_3e_10892',['Pointer&lt; IBAMR::INSStaggeredHierarchyIntegrator &gt;',['../../../samrai/2.4.4/html/classSAMRAI_1_1tbox_1_1Pointer.html',1,'SAMRAI::tbox']]],
  ['pointer_3c_20ibamr_3a_3ainsvcstaggeredhierarchyintegrator_20_3e_10893',['Pointer&lt; IBAMR::INSVCStaggeredHierarchyIntegrator &gt;',['../../../samrai/2.4.4/html/classSAMRAI_1_1tbox_1_1Pointer.html',1,'SAMRAI::tbox']]],
  ['pointer_3c_20ibamr_3a_3akrylovfreebodymobilitysolver_20_3e_10894',['Pointer&lt; IBAMR::KrylovFreeBodyMobilitySolver &gt;',['../../../samrai/2.4.4/html/classSAMRAI_1_1tbox_1_1Pointer.html',1,'SAMRAI::tbox']]],
  ['pointer_3c_20ibamr_3a_3akrylovmobilitysolver_20_3e_10895',['Pointer&lt; IBAMR::KrylovMobilitySolver &gt;',['../../../samrai/2.4.4/html/classSAMRAI_1_1tbox_1_1Pointer.html',1,'SAMRAI::tbox']]],
  ['pointer_3c_20ibamr_3a_3aphasechangehierarchyintegrator_20_3e_10896',['Pointer&lt; IBAMR::PhaseChangeHierarchyIntegrator &gt;',['../../../samrai/2.4.4/html/classSAMRAI_1_1tbox_1_1Pointer.html',1,'SAMRAI::tbox']]],
  ['pointer_3c_20ibamr_3a_3astaggeredstokesfacpreconditioner_20_3e_10897',['Pointer&lt; IBAMR::StaggeredStokesFACPreconditioner &gt;',['../../../samrai/2.4.4/html/classSAMRAI_1_1tbox_1_1Pointer.html',1,'SAMRAI::tbox']]],
  ['pointer_3c_20ibamr_3a_3astaggeredstokesoperator_20_3e_10898',['Pointer&lt; IBAMR::StaggeredStokesOperator &gt;',['../../../samrai/2.4.4/html/classSAMRAI_1_1tbox_1_1Pointer.html',1,'SAMRAI::tbox']]],
  ['pointer_3c_20ibamr_3a_3astaggeredstokesphysicalboundaryhelper_20_3e_10899',['Pointer&lt; IBAMR::StaggeredStokesPhysicalBoundaryHelper &gt;',['../../../samrai/2.4.4/html/classSAMRAI_1_1tbox_1_1Pointer.html',1,'SAMRAI::tbox']]],
  ['pointer_3c_20ibamr_3a_3astaggeredstokessolver_20_3e_10900',['Pointer&lt; IBAMR::StaggeredStokesSolver &gt;',['../../../samrai/2.4.4/html/classSAMRAI_1_1tbox_1_1Pointer.html',1,'SAMRAI::tbox']]],
  ['pointer_3c_20ibamr_3a_3astsmassfluxintegrator_20_3e_10901',['Pointer&lt; IBAMR::STSMassFluxIntegrator &gt;',['../../../samrai/2.4.4/html/classSAMRAI_1_1tbox_1_1Pointer.html',1,'SAMRAI::tbox']]],
  ['pointer_3c_20ibtk_3a_3acartcellrobinphysbdryop_20_3e_10902',['Pointer&lt; IBTK::CartCellRobinPhysBdryOp &gt;',['../../../samrai/2.4.4/html/classSAMRAI_1_1tbox_1_1Pointer.html',1,'SAMRAI::tbox']]],
  ['pointer_3c_20ibtk_3a_3acartgridfunction_20_3e_10903',['Pointer&lt; IBTK::CartGridFunction &gt;',['../../../samrai/2.4.4/html/classSAMRAI_1_1tbox_1_1Pointer.html',1,'SAMRAI::tbox']]],
  ['pointer_3c_20ibtk_3a_3acartsiderobinphysbdryop_20_3e_10904',['Pointer&lt; IBTK::CartSideRobinPhysBdryOp &gt;',['../../../samrai/2.4.4/html/classSAMRAI_1_1tbox_1_1Pointer.html',1,'SAMRAI::tbox']]],
  ['pointer_3c_20ibtk_3a_3acclaplaceoperator_20_3e_10905',['Pointer&lt; IBTK::CCLaplaceOperator &gt;',['../../../samrai/2.4.4/html/classSAMRAI_1_1tbox_1_1Pointer.html',1,'SAMRAI::tbox']]],
  ['pointer_3c_20ibtk_3a_3accpoissonpointrelaxationfacoperator_20_3e_10906',['Pointer&lt; IBTK::CCPoissonPointRelaxationFACOperator &gt;',['../../../samrai/2.4.4/html/classSAMRAI_1_1tbox_1_1Pointer.html',1,'SAMRAI::tbox']]],
  ['pointer_3c_20ibtk_3a_3acoarsefineboundaryrefinepatchstrategy_20_3e_10907',['Pointer&lt; IBTK::CoarseFineBoundaryRefinePatchStrategy &gt;',['../../../samrai/2.4.4/html/classSAMRAI_1_1tbox_1_1Pointer.html',1,'SAMRAI::tbox']]],
  ['pointer_3c_20ibtk_3a_3afacpreconditioner_20_3e_10908',['Pointer&lt; IBTK::FACPreconditioner &gt;',['../../../samrai/2.4.4/html/classSAMRAI_1_1tbox_1_1Pointer.html',1,'SAMRAI::tbox']]],
  ['pointer_3c_20ibtk_3a_3afacpreconditionerstrategy_20_3e_10909',['Pointer&lt; IBTK::FACPreconditionerStrategy &gt;',['../../../samrai/2.4.4/html/classSAMRAI_1_1tbox_1_1Pointer.html',1,'SAMRAI::tbox']]],
  ['pointer_3c_20ibtk_3a_3ageneraloperator_20_3e_10910',['Pointer&lt; IBTK::GeneralOperator &gt;',['../../../samrai/2.4.4/html/classSAMRAI_1_1tbox_1_1Pointer.html',1,'SAMRAI::tbox']]],
  ['pointer_3c_20ibtk_3a_3ahierarchyghostcellinterpolation_20_3e_10911',['Pointer&lt; IBTK::HierarchyGhostCellInterpolation &gt;',['../../../samrai/2.4.4/html/classSAMRAI_1_1tbox_1_1Pointer.html',1,'SAMRAI::tbox']]],
  ['pointer_3c_20ibtk_3a_3ahierarchymathops_20_3e_10912',['Pointer&lt; IBTK::HierarchyMathOps &gt;',['../../../samrai/2.4.4/html/classSAMRAI_1_1tbox_1_1Pointer.html',1,'SAMRAI::tbox']]],
  ['pointer_3c_20ibtk_3a_3ajacobianoperator_20_3e_10913',['Pointer&lt; IBTK::JacobianOperator &gt;',['../../../samrai/2.4.4/html/classSAMRAI_1_1tbox_1_1Pointer.html',1,'SAMRAI::tbox']]],
  ['pointer_3c_20ibtk_3a_3akrylovlinearsolver_20_3e_10914',['Pointer&lt; IBTK::KrylovLinearSolver &gt;',['../../../samrai/2.4.4/html/classSAMRAI_1_1tbox_1_1Pointer.html',1,'SAMRAI::tbox']]],
  ['pointer_3c_20ibtk_3a_3alaplaceoperator_20_3e_10915',['Pointer&lt; IBTK::LaplaceOperator &gt;',['../../../samrai/2.4.4/html/classSAMRAI_1_1tbox_1_1Pointer.html',1,'SAMRAI::tbox']]],
  ['pointer_3c_20ibtk_3a_3alindexsetvariable_20_3e_10916',['Pointer&lt; IBTK::LIndexSetVariable &gt;',['../../../samrai/2.4.4/html/classSAMRAI_1_1tbox_1_1Pointer.html',1,'SAMRAI::tbox']]],
  ['pointer_3c_20ibtk_3a_3alinearoperator_20_3e_10917',['Pointer&lt; IBTK::LinearOperator &gt;',['../../../samrai/2.4.4/html/classSAMRAI_1_1tbox_1_1Pointer.html',1,'SAMRAI::tbox']]],
  ['pointer_3c_20ibtk_3a_3alinearsolver_20_3e_10918',['Pointer&lt; IBTK::LinearSolver &gt;',['../../../samrai/2.4.4/html/classSAMRAI_1_1tbox_1_1Pointer.html',1,'SAMRAI::tbox']]],
  ['pointer_3c_20ibtk_3a_3alinitstrategy_20_3e_10919',['Pointer&lt; IBTK::LInitStrategy &gt;',['../../../samrai/2.4.4/html/classSAMRAI_1_1tbox_1_1Pointer.html',1,'SAMRAI::tbox']]],
  ['pointer_3c_20ibtk_3a_3alsilodatawriter_20_3e_10920',['Pointer&lt; IBTK::LSiloDataWriter &gt;',['../../../samrai/2.4.4/html/classSAMRAI_1_1tbox_1_1Pointer.html',1,'SAMRAI::tbox']]],
  ['pointer_3c_20ibtk_3a_3amarkerpatchhierarchy_20_3e_10921',['Pointer&lt; IBTK::MarkerPatchHierarchy &gt;',['../../../samrai/2.4.4/html/classSAMRAI_1_1tbox_1_1Pointer.html',1,'SAMRAI::tbox']]],
  ['pointer_3c_20ibtk_3a_3amuparsercartgridfunction_20_3e_10922',['Pointer&lt; IBTK::muParserCartGridFunction &gt;',['../../../samrai/2.4.4/html/classSAMRAI_1_1tbox_1_1Pointer.html',1,'SAMRAI::tbox']]],
  ['pointer_3c_20ibtk_3a_3apetsckrylovpoissonsolver_20_3e_10923',['Pointer&lt; IBTK::PETScKrylovPoissonSolver &gt;',['../../../samrai/2.4.4/html/classSAMRAI_1_1tbox_1_1Pointer.html',1,'SAMRAI::tbox']]],
  ['pointer_3c_20ibtk_3a_3apetscnewtonkrylovsolver_20_3e_10924',['Pointer&lt; IBTK::PETScNewtonKrylovSolver &gt;',['../../../samrai/2.4.4/html/classSAMRAI_1_1tbox_1_1Pointer.html',1,'SAMRAI::tbox']]],
  ['pointer_3c_20ibtk_3a_3apoissonsolver_20_3e_10925',['Pointer&lt; IBTK::PoissonSolver &gt;',['../../../samrai/2.4.4/html/classSAMRAI_1_1tbox_1_1Pointer.html',1,'SAMRAI::tbox']]],
  ['pointer_3c_20ibtk_3a_3arobinphysbdrypatchstrategy_20_3e_10926',['Pointer&lt; IBTK::RobinPhysBdryPatchStrategy &gt;',['../../../samrai/2.4.4/html/classSAMRAI_1_1tbox_1_1Pointer.html',1,'SAMRAI::tbox']]],
  ['pointer_3c_20ibtk_3a_3asidedatasynchronization_20_3e_10927',['Pointer&lt; IBTK::SideDataSynchronization &gt;',['../../../samrai/2.4.4/html/classSAMRAI_1_1tbox_1_1Pointer.html',1,'SAMRAI::tbox']]],
  ['pointer_3c_20ibtk_3a_3astaggeredphysicalboundaryhelper_20_3e_10928',['Pointer&lt; IBTK::StaggeredPhysicalBoundaryHelper &gt;',['../../../samrai/2.4.4/html/classSAMRAI_1_1tbox_1_1Pointer.html',1,'SAMRAI::tbox']]],
  ['pointer_3c_20regriddata_20_3e_10929',['Pointer&lt; RegridData &gt;',['../../../samrai/2.4.4/html/classSAMRAI_1_1tbox_1_1Pointer.html',1,'SAMRAI::tbox']]],
  ['pointer_3c_20samrai_3a_3aalgs_3a_3ahyperboliclevelintegrator_3c_20ndim_20_3e_20_3e_10930',['Pointer&lt; SAMRAI::algs::HyperbolicLevelIntegrator&lt; NDIM &gt; &gt;',['../../../samrai/2.4.4/html/classSAMRAI_1_1tbox_1_1Pointer.html',1,'SAMRAI::tbox']]],
  ['pointer_3c_20samrai_3a_3aappu_3a_3avisitdatawriter_3c_20ndim_20_3e_20_3e_10931',['Pointer&lt; SAMRAI::appu::VisItDataWriter&lt; NDIM &gt; &gt;',['../../../samrai/2.4.4/html/classSAMRAI_1_1tbox_1_1Pointer.html',1,'SAMRAI::tbox']]],
  ['pointer_3c_20samrai_3a_3ageom_3a_3acartesiangridgeometry_3c_20ndim_20_3e_20_3e_10932',['Pointer&lt; SAMRAI::geom::CartesianGridGeometry&lt; NDIM &gt; &gt;',['../../../samrai/2.4.4/html/classSAMRAI_1_1tbox_1_1Pointer.html',1,'SAMRAI::tbox']]],
  ['pointer_3c_20samrai_3a_3ahier_3a_3abasepatchhierarchy_3c_20ndim_20_3e_20_3e_10933',['Pointer&lt; SAMRAI::hier::BasePatchHierarchy&lt; NDIM &gt; &gt;',['../../../samrai/2.4.4/html/classSAMRAI_1_1tbox_1_1Pointer.html',1,'SAMRAI::tbox']]],
  ['pointer_3c_20samrai_3a_3ahier_3a_3acoarsefineboundary_3c_20ndim_20_3e_20_3e_10934',['Pointer&lt; SAMRAI::hier::CoarseFineBoundary&lt; NDIM &gt; &gt;',['../../../samrai/2.4.4/html/classSAMRAI_1_1tbox_1_1Pointer.html',1,'SAMRAI::tbox']]],
  ['pointer_3c_20samrai_3a_3ahier_3a_3apatch_3c_20dim_20_3e_20_3e_10935',['Pointer&lt; SAMRAI::hier::Patch&lt; DIM &gt; &gt;',['../../../samrai/2.4.4/html/classSAMRAI_1_1tbox_1_1Pointer.html',1,'SAMRAI::tbox']]],
  ['pointer_3c_20samrai_3a_3ahier_3a_3apatchdata_3c_20ndim_20_3e_20_3e_10936',['Pointer&lt; SAMRAI::hier::PatchData&lt; NDIM &gt; &gt;',['../../../samrai/2.4.4/html/classSAMRAI_1_1tbox_1_1Pointer.html',1,'SAMRAI::tbox']]],
  ['pointer_3c_20samrai_3a_3ahier_3a_3apatchhierarchy_3c_20ndim_20_3e_20_3e_10937',['Pointer&lt; SAMRAI::hier::PatchHierarchy&lt; NDIM &gt; &gt;',['../../../samrai/2.4.4/html/classSAMRAI_1_1tbox_1_1Pointer.html',1,'SAMRAI::tbox']]],
  ['pointer_3c_20samrai_3a_3ahier_3a_3apatchlevel_3c_20dim_20_3e_20_3e_10938',['Pointer&lt; SAMRAI::hier::PatchLevel&lt; DIM &gt; &gt;',['../../../samrai/2.4.4/html/classSAMRAI_1_1tbox_1_1Pointer.html',1,'SAMRAI::tbox']]],
  ['pointer_3c_20samrai_3a_3ahier_3a_3apatchlevel_3c_20ndim_20_3e_20_3e_10939',['Pointer&lt; SAMRAI::hier::PatchLevel&lt; NDIM &gt; &gt;',['../../../samrai/2.4.4/html/classSAMRAI_1_1tbox_1_1Pointer.html',1,'SAMRAI::tbox']]],
  ['pointer_3c_20samrai_3a_3ahier_3a_3avariable_3c_20ndim_20_3e_20_3e_10940',['Pointer&lt; SAMRAI::hier::Variable&lt; NDIM &gt; &gt;',['../../../samrai/2.4.4/html/classSAMRAI_1_1tbox_1_1Pointer.html',1,'SAMRAI::tbox']]],
  ['pointer_3c_20samrai_3a_3ahier_3a_3avariablecontext_20_3e_10941',['Pointer&lt; SAMRAI::hier::VariableContext &gt;',['../../../samrai/2.4.4/html/classSAMRAI_1_1tbox_1_1Pointer.html',1,'SAMRAI::tbox']]],
  ['pointer_3c_20samrai_3a_3amath_3a_3ahierarchycelldataopsreal_3c_20ndim_2c_20double_20_3e_20_3e_10942',['Pointer&lt; SAMRAI::math::HierarchyCellDataOpsReal&lt; NDIM, double &gt; &gt;',['../../../samrai/2.4.4/html/classSAMRAI_1_1tbox_1_1Pointer.html',1,'SAMRAI::tbox']]],
  ['pointer_3c_20samrai_3a_3amath_3a_3ahierarchydataopsreal_3c_20ndim_2c_20double_20_3e_20_3e_10943',['Pointer&lt; SAMRAI::math::HierarchyDataOpsReal&lt; NDIM, double &gt; &gt;',['../../../samrai/2.4.4/html/classSAMRAI_1_1tbox_1_1Pointer.html',1,'SAMRAI::tbox']]],
  ['pointer_3c_20samrai_3a_3amath_3a_3ahierarchyedgedataopsreal_3c_20ndim_2c_20double_20_3e_20_3e_10944',['Pointer&lt; SAMRAI::math::HierarchyEdgeDataOpsReal&lt; NDIM, double &gt; &gt;',['../../../samrai/2.4.4/html/classSAMRAI_1_1tbox_1_1Pointer.html',1,'SAMRAI::tbox']]],
  ['pointer_3c_20samrai_3a_3amath_3a_3ahierarchyfacedataopsreal_3c_20ndim_2c_20double_20_3e_20_3e_10945',['Pointer&lt; SAMRAI::math::HierarchyFaceDataOpsReal&lt; NDIM, double &gt; &gt;',['../../../samrai/2.4.4/html/classSAMRAI_1_1tbox_1_1Pointer.html',1,'SAMRAI::tbox']]],
  ['pointer_3c_20samrai_3a_3amath_3a_3ahierarchynodedataopsreal_3c_20ndim_2c_20double_20_3e_20_3e_10946',['Pointer&lt; SAMRAI::math::HierarchyNodeDataOpsReal&lt; NDIM, double &gt; &gt;',['../../../samrai/2.4.4/html/classSAMRAI_1_1tbox_1_1Pointer.html',1,'SAMRAI::tbox']]],
  ['pointer_3c_20samrai_3a_3amath_3a_3ahierarchysidedataopsreal_3c_20ndim_2c_20double_20_3e_20_3e_10947',['Pointer&lt; SAMRAI::math::HierarchySideDataOpsReal&lt; NDIM, double &gt; &gt;',['../../../samrai/2.4.4/html/classSAMRAI_1_1tbox_1_1Pointer.html',1,'SAMRAI::tbox']]],
  ['pointer_3c_20samrai_3a_3amesh_3a_3aboxgeneratorstrategy_3c_20ndim_20_3e_20_3e_10948',['Pointer&lt; SAMRAI::mesh::BoxGeneratorStrategy&lt; NDIM &gt; &gt;',['../../../samrai/2.4.4/html/classSAMRAI_1_1tbox_1_1Pointer.html',1,'SAMRAI::tbox']]],
  ['pointer_3c_20samrai_3a_3amesh_3a_3agriddingalgorithm_3c_20ndim_20_3e_20_3e_10949',['Pointer&lt; SAMRAI::mesh::GriddingAlgorithm&lt; NDIM &gt; &gt;',['../../../samrai/2.4.4/html/classSAMRAI_1_1tbox_1_1Pointer.html',1,'SAMRAI::tbox']]],
  ['pointer_3c_20samrai_3a_3amesh_3a_3aloadbalancer_3c_20ndim_20_3e_20_3e_10950',['Pointer&lt; SAMRAI::mesh::LoadBalancer&lt; NDIM &gt; &gt;',['../../../samrai/2.4.4/html/classSAMRAI_1_1tbox_1_1Pointer.html',1,'SAMRAI::tbox']]],
  ['pointer_3c_20samrai_3a_3amesh_3a_3atagandinitializestrategy_3c_20ndim_20_3e_20_3e_10951',['Pointer&lt; SAMRAI::mesh::TagAndInitializeStrategy&lt; NDIM &gt; &gt;',['../../../samrai/2.4.4/html/classSAMRAI_1_1tbox_1_1Pointer.html',1,'SAMRAI::tbox']]],
  ['pointer_3c_20samrai_3a_3apdat_3a_3acellvariable_3c_20ndim_2c_20double_20_3e_20_3e_10952',['Pointer&lt; SAMRAI::pdat::CellVariable&lt; NDIM, double &gt; &gt;',['../../../samrai/2.4.4/html/classSAMRAI_1_1tbox_1_1Pointer.html',1,'SAMRAI::tbox']]],
  ['pointer_3c_20samrai_3a_3apdat_3a_3acellvariable_3c_20ndim_2c_20int_20_3e_20_3e_10953',['Pointer&lt; SAMRAI::pdat::CellVariable&lt; NDIM, int &gt; &gt;',['../../../samrai/2.4.4/html/classSAMRAI_1_1tbox_1_1Pointer.html',1,'SAMRAI::tbox']]],
  ['pointer_3c_20samrai_3a_3apdat_3a_3aedgevariable_3c_20ndim_2c_20double_20_3e_20_3e_10954',['Pointer&lt; SAMRAI::pdat::EdgeVariable&lt; NDIM, double &gt; &gt;',['../../../samrai/2.4.4/html/classSAMRAI_1_1tbox_1_1Pointer.html',1,'SAMRAI::tbox']]],
  ['pointer_3c_20samrai_3a_3apdat_3a_3afacevariable_3c_20ndim_2c_20double_20_3e_20_3e_10955',['Pointer&lt; SAMRAI::pdat::FaceVariable&lt; NDIM, double &gt; &gt;',['../../../samrai/2.4.4/html/classSAMRAI_1_1tbox_1_1Pointer.html',1,'SAMRAI::tbox']]],
  ['pointer_3c_20samrai_3a_3apdat_3a_3anodevariable_3c_20ndim_2c_20double_20_3e_20_3e_10956',['Pointer&lt; SAMRAI::pdat::NodeVariable&lt; NDIM, double &gt; &gt;',['../../../samrai/2.4.4/html/classSAMRAI_1_1tbox_1_1Pointer.html',1,'SAMRAI::tbox']]],
  ['pointer_3c_20samrai_3a_3apdat_3a_3aouteredgevariable_3c_20ndim_2c_20double_20_3e_20_3e_10957',['Pointer&lt; SAMRAI::pdat::OuteredgeVariable&lt; NDIM, double &gt; &gt;',['../../../samrai/2.4.4/html/classSAMRAI_1_1tbox_1_1Pointer.html',1,'SAMRAI::tbox']]],
  ['pointer_3c_20samrai_3a_3apdat_3a_3aouterfacevariable_3c_20ndim_2c_20double_20_3e_20_3e_10958',['Pointer&lt; SAMRAI::pdat::OuterfaceVariable&lt; NDIM, double &gt; &gt;',['../../../samrai/2.4.4/html/classSAMRAI_1_1tbox_1_1Pointer.html',1,'SAMRAI::tbox']]],
  ['pointer_3c_20samrai_3a_3apdat_3a_3aouternodevariable_3c_20ndim_2c_20double_20_3e_20_3e_10959',['Pointer&lt; SAMRAI::pdat::OuternodeVariable&lt; NDIM, double &gt; &gt;',['../../../samrai/2.4.4/html/classSAMRAI_1_1tbox_1_1Pointer.html',1,'SAMRAI::tbox']]],
  ['pointer_3c_20samrai_3a_3apdat_3a_3aoutersidevariable_3c_20ndim_2c_20double_20_3e_20_3e_10960',['Pointer&lt; SAMRAI::pdat::OutersideVariable&lt; NDIM, double &gt; &gt;',['../../../samrai/2.4.4/html/classSAMRAI_1_1tbox_1_1Pointer.html',1,'SAMRAI::tbox']]],
  ['pointer_3c_20samrai_3a_3apdat_3a_3asidevariable_3c_20ndim_2c_20double_20_3e_20_3e_10961',['Pointer&lt; SAMRAI::pdat::SideVariable&lt; NDIM, double &gt; &gt;',['../../../samrai/2.4.4/html/classSAMRAI_1_1tbox_1_1Pointer.html',1,'SAMRAI::tbox']]],
  ['pointer_3c_20samrai_3a_3apdat_3a_3asidevariable_3c_20ndim_2c_20int_20_3e_20_3e_10962',['Pointer&lt; SAMRAI::pdat::SideVariable&lt; NDIM, int &gt; &gt;',['../../../samrai/2.4.4/html/classSAMRAI_1_1tbox_1_1Pointer.html',1,'SAMRAI::tbox']]],
  ['pointer_3c_20samrai_3a_3asolv_3a_3asamraivectorreal_3c_20ndim_2c_20double_20_3e_20_3e_10963',['Pointer&lt; SAMRAI::solv::SAMRAIVectorReal&lt; NDIM, double &gt; &gt;',['../../../samrai/2.4.4/html/classSAMRAI_1_1tbox_1_1Pointer.html',1,'SAMRAI::tbox']]],
  ['pointer_3c_20samrai_3a_3asolv_3a_3asamraivectorreal_3c_20ndim_2c_20petscscalar_20_3e_20_3e_10964',['Pointer&lt; SAMRAI::solv::SAMRAIVectorReal&lt; NDIM, PetscScalar &gt; &gt;',['../../../samrai/2.4.4/html/classSAMRAI_1_1tbox_1_1Pointer.html',1,'SAMRAI::tbox']]],
  ['pointer_3c_20samrai_3a_3asolv_3a_3asamraivectorreal_3c_20ndim_2c_20type_20_3e_20_3e_10965',['Pointer&lt; SAMRAI::solv::SAMRAIVectorReal&lt; NDIM, TYPE &gt; &gt;',['../../../samrai/2.4.4/html/classSAMRAI_1_1tbox_1_1Pointer.html',1,'SAMRAI::tbox']]],
  ['pointer_3c_20samrai_3a_3atbox_3a_3adatabase_20_3e_10966',['Pointer&lt; SAMRAI::tbox::Database &gt;',['../../../samrai/2.4.4/html/classSAMRAI_1_1tbox_1_1Pointer.html',1,'SAMRAI::tbox']]],
  ['pointer_3c_20samrai_3a_3atbox_3a_3amessagestream_20_3e_10967',['Pointer&lt; SAMRAI::tbox::MessageStream &gt;',['../../../samrai/2.4.4/html/classSAMRAI_1_1tbox_1_1Pointer.html',1,'SAMRAI::tbox']]],
  ['pointer_3c_20samrai_3a_3atbox_3a_3atimer_20_3e_10968',['Pointer&lt; SAMRAI::tbox::Timer &gt;',['../../../samrai/2.4.4/html/classSAMRAI_1_1tbox_1_1Pointer.html',1,'SAMRAI::tbox']]],
  ['pointer_3c_20samrai_3a_3axfer_3a_3acoarsenalgorithm_3c_20ndim_20_3e_20_3e_10969',['Pointer&lt; SAMRAI::xfer::CoarsenAlgorithm&lt; NDIM &gt; &gt;',['../../../samrai/2.4.4/html/classSAMRAI_1_1tbox_1_1Pointer.html',1,'SAMRAI::tbox']]],
  ['pointer_3c_20samrai_3a_3axfer_3a_3acoarsenoperator_3c_20dim_20_3e_20_3e_10970',['Pointer&lt; SAMRAI::xfer::CoarsenOperator&lt; DIM &gt; &gt;',['../../../samrai/2.4.4/html/classSAMRAI_1_1tbox_1_1Pointer.html',1,'SAMRAI::tbox']]],
  ['pointer_3c_20samrai_3a_3axfer_3a_3acoarsenoperator_3c_20ndim_20_3e_20_3e_10971',['Pointer&lt; SAMRAI::xfer::CoarsenOperator&lt; NDIM &gt; &gt;',['../../../samrai/2.4.4/html/classSAMRAI_1_1tbox_1_1Pointer.html',1,'SAMRAI::tbox']]],
  ['pointer_3c_20samrai_3a_3axfer_3a_3arefinealgorithm_3c_20ndim_20_3e_20_3e_10972',['Pointer&lt; SAMRAI::xfer::RefineAlgorithm&lt; NDIM &gt; &gt;',['../../../samrai/2.4.4/html/classSAMRAI_1_1tbox_1_1Pointer.html',1,'SAMRAI::tbox']]],
  ['pointer_3c_20samrai_3a_3axfer_3a_3arefineoperator_3c_20dim_20_3e_20_3e_10973',['Pointer&lt; SAMRAI::xfer::RefineOperator&lt; DIM &gt; &gt;',['../../../samrai/2.4.4/html/classSAMRAI_1_1tbox_1_1Pointer.html',1,'SAMRAI::tbox']]],
  ['pointer_3c_20samrai_3a_3axfer_3a_3arefineoperator_3c_20ndim_20_3e_20_3e_10974',['Pointer&lt; SAMRAI::xfer::RefineOperator&lt; NDIM &gt; &gt;',['../../../samrai/2.4.4/html/classSAMRAI_1_1tbox_1_1Pointer.html',1,'SAMRAI::tbox']]],
  ['pointer_3c_20samrai_3a_3axfer_3a_3arefinepatchstrategy_3c_20ndim_20_3e_20_3e_10975',['Pointer&lt; SAMRAI::xfer::RefinePatchStrategy&lt; NDIM &gt; &gt;',['../../../samrai/2.4.4/html/classSAMRAI_1_1tbox_1_1Pointer.html',1,'SAMRAI::tbox']]],
  ['pointer_3c_20samrai_3a_3axfer_3a_3arefineschedule_3c_20ndim_20_3e_20_3e_10976',['Pointer&lt; SAMRAI::xfer::RefineSchedule&lt; NDIM &gt; &gt;',['../../../samrai/2.4.4/html/classSAMRAI_1_1tbox_1_1Pointer.html',1,'SAMRAI::tbox']]],
  ['pointer_3c_20samrai_3a_3axfer_3a_3atimeinterpolateoperator_3c_20dim_20_3e_20_3e_10977',['Pointer&lt; SAMRAI::xfer::TimeInterpolateOperator&lt; DIM &gt; &gt;',['../../../samrai/2.4.4/html/classSAMRAI_1_1tbox_1_1Pointer.html',1,'SAMRAI::tbox']]],
  ['pointer_3c_20samrai_3a_3axfer_3a_3avariablefillpattern_3c_20dim_20_3e_20_3e_10978',['Pointer&lt; SAMRAI::xfer::VariableFillPattern&lt; DIM &gt; &gt;',['../../../samrai/2.4.4/html/classSAMRAI_1_1tbox_1_1Pointer.html',1,'SAMRAI::tbox']]],
  ['pointer_3c_20samrai_3a_3axfer_3a_3avariablefillpattern_3c_20ndim_20_3e_20_3e_10979',['Pointer&lt; SAMRAI::xfer::VariableFillPattern&lt; NDIM &gt; &gt;',['../../../samrai/2.4.4/html/classSAMRAI_1_1tbox_1_1Pointer.html',1,'SAMRAI::tbox']]],
  ['pointer_5fto_5fbinary_5ffunction_10980',['pointer_to_binary_function',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a08135.html',1,'std']]],
  ['pointer_5fto_5funary_5ffunction_10981',['pointer_to_unary_function',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a08131.html',1,'std']]],
  ['pointer_5ftraits_10982',['pointer_traits',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a06463.html',1,'std']]],
  ['pointer_5ftraits_3c_20_5ftp_20_2a_20_3e_10983',['pointer_traits&lt; _Tp * &gt;',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a06467.html',1,'std']]],
  ['pointerbase_10984',['PointerBase',['../../../samrai/2.4.4/html/classSAMRAI_1_1tbox_1_1PointerBase.html',1,'SAMRAI::tbox']]],
  ['poisson_5fdistribution_10985',['poisson_distribution',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a06611.html',1,'std']]],
  ['poissonfacpreconditioner_10986',['PoissonFACPreconditioner',['../class_i_b_t_k_1_1_poisson_f_a_c_preconditioner.html',1,'IBTK']]],
  ['poissonfacpreconditionerstrategy_10987',['PoissonFACPreconditionerStrategy',['../class_i_b_t_k_1_1_poisson_f_a_c_preconditioner_strategy.html',1,'IBTK']]],
  ['poissonsolver_10988',['PoissonSolver',['../class_i_b_t_k_1_1_poisson_solver.html',1,'IBTK']]],
  ['poissonspecifications_10989',['PoissonSpecifications',['../../../samrai/2.4.4/html/classSAMRAI_1_1solv_1_1PoissonSpecifications.html',1,'SAMRAI::solv']]],
  ['poissonutilities_10990',['PoissonUtilities',['../class_i_b_t_k_1_1_poisson_utilities.html',1,'IBTK']]],
  ['pool_5foptions_10991',['pool_options',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a02775.html',1,'std::pmr']]],
  ['priority_5fqueue_10992',['priority_queue',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a12595.html',1,'__gnu_pbds::priority_queue&lt; typename _Tv, typename Cmp_Fn, typename Tag, typename _Alloc &gt;'],['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a08451.html',1,'std::priority_queue&lt; typename _Tp, typename _Sequence, typename _Compare &gt;']]],
  ['priority_5fqueue_5ftag_10993',['priority_queue_tag',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a12675.html',1,'__gnu_pbds']]],
  ['probe_5ffn_5fbase_10994',['probe_fn_base',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a13115.html',1,'__gnu_pbds::detail']]],
  ['processormapping_10995',['ProcessorMapping',['../../../samrai/2.4.4/html/classSAMRAI_1_1hier_1_1ProcessorMapping.html',1,'SAMRAI::hier']]],
  ['procstat_10996',['ProcStat',['../../../samrai/2.4.4/html/structSAMRAI_1_1tbox_1_1Statistic_1_1ProcStat.html',1,'SAMRAI::tbox::Statistic']]],
  ['project1st_10997',['project1st',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a09587.html',1,'__gnu_cxx']]],
  ['project2nd_10998',['project2nd',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a09591.html',1,'__gnu_cxx']]],
  ['projected_10999',['projected',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a05963.html',1,'std']]],
  ['promise_11000',['promise',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a02543.html',1,'std']]],
  ['promise_3c_20_5fres_20_26_20_3e_11001',['promise&lt; _Res &amp; &gt;',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a02575.html',1,'std']]],
  ['promise_3c_20void_20_3e_11002',['promise&lt; void &gt;',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a02579.html',1,'std']]],
  ['propagate_5fconst_11003',['propagate_const',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a11535.html',1,'std::experimental::fundamentals_v2']]]
];
