var searchData=
[
  ['samr_20meshes_0',['samr meshes',['../../../samrai/2.4.4/html/package_algorithm_femutils.html',1,'Rudimentary Support for Finite Element Operations on SAMR Meshes'],['../../../samrai/2.4.4/html/package_transfer_datamovers.html',1,'Support for Moving Data on SAMR Meshes']]],
  ['samrai_20hierarchy_1',['samrai hierarchy',['../../../samrai/2.4.4/html/package_solvers_FAC.html',1,'FAC preconditioner on a SAMRAI hierarchy'],['../../../samrai/2.4.4/html/package_solvers_poisson.html',1,'Poisson solvers on a SAMRAI hierarchy']]],
  ['samrai_20source_20code_20documentation_2',['SAMRAI Source Code Documentation',['../../../samrai/2.4.4/html/main.html',1,'']]],
  ['samrai_20vector_20facilities_3',['SAMRAI Vector Facilities',['../../../samrai/2.4.4/html/package_solvers_vectors.html',1,'']]],
  ['side_20patch_20data_4',['Side Patch Data',['../../../samrai/2.4.4/html/package_patchdata_side.html',1,'']]],
  ['skeleton_20geometry_20support_5',['Skeleton Geometry Support',['../../../samrai/2.4.4/html/package_geometry_skeleton.html',1,'']]],
  ['skeleton_20grid_20geometry_6',['Skeleton Grid Geometry',['../../../samrai/2.4.4/html/package_geometry_skeleton_grid_geom.html',1,'']]],
  ['skeleton_20operators_7',['Skeleton Operators',['../../../samrai/2.4.4/html/package_geometry_skeleton_operators.html',1,'']]],
  ['skeleton_20patch_20geometry_8',['Skeleton Patch Geometry',['../../../samrai/2.4.4/html/package_geometry_skeleton_patch_geom.html',1,'']]],
  ['solver_9',['Nonlinear solver',['../../../samrai/2.4.4/html/package_solvers_nonlinear.html',1,'']]],
  ['solver_20interface_10',['solver interface',['../../../samrai/2.4.4/html/package_solvers_packages_sundials_cvode.html',1,'CVODE ODE solver interface'],['../../../samrai/2.4.4/html/package_solvers_packages_sundials_kinsol.html',1,'KINSOL Vector and Nonlinear Solver Interface']]],
  ['solver_20libraries_11',['Interfaces to Solver Libraries',['../../../samrai/2.4.4/html/package_solvers_packages.html',1,'']]],
  ['solver_20package_12',['The Solver Package',['../../../samrai/2.4.4/html/package_solvers.html',1,'']]],
  ['solvers_13',['Interfaces for the Sundials of Solvers',['../../../samrai/2.4.4/html/package_solvers_packages_sundials.html',1,'']]],
  ['solvers_20on_20a_20samrai_20hierarchy_14',['Poisson solvers on a SAMRAI hierarchy',['../../../samrai/2.4.4/html/package_solvers_poisson.html',1,'']]],
  ['source_20code_20documentation_15',['SAMRAI Source Code Documentation',['../../../samrai/2.4.4/html/main.html',1,'']]],
  ['standard_20data_20communication_20classes_16',['Standard Data Communication Classes',['../../../samrai/2.4.4/html/package_transfer_datamovers_standard.html',1,'']]],
  ['standard_20data_20summation_20operations_17',['Standard Data Summation Operations',['../../../samrai/2.4.4/html/package_algorithm_femutils_standard.html',1,'']]],
  ['stream_20toolbox_20classes_18',['Stream Toolbox Classes',['../../../samrai/2.4.4/html/package_toolbox_stream.html',1,'']]],
  ['structures_19',['Patch Adjacency Graph Structures',['../../../samrai/2.4.4/html/package_hierarchy_dlbg.html',1,'']]],
  ['summation_20operations_20',['summation operations',['../../../samrai/2.4.4/html/package_algorithm_femutils_locallyactive.html',1,'Locally-active Data Summation Operations'],['../../../samrai/2.4.4/html/package_algorithm_femutils_standard.html',1,'Standard Data Summation Operations']]],
  ['sundials_20of_20solvers_21',['Interfaces for the Sundials of Solvers',['../../../samrai/2.4.4/html/package_solvers_packages_sundials.html',1,'']]],
  ['sundials_20vector_20interface_22',['Sundials Vector Interface',['../../../samrai/2.4.4/html/package_solvers_packages_sundials_vector.html',1,'']]],
  ['support_23',['support',['../../../samrai/2.4.4/html/package_patchdata_array.html',1,'Array-based Patch Data Support'],['../../../samrai/2.4.4/html/package_geometry_cartesian.html',1,'Basic Cartesian Mesh Geometry Support'],['../../../samrai/2.4.4/html/package_geometry_multiblock.html',1,'Basic Multiblock Geometry Support'],['../../../samrai/2.4.4/html/package_toolbox_database.html',1,'Generic Database Support'],['../../../samrai/2.4.4/html/package_toolbox_memory.html',1,'Memory Support'],['../../../samrai/2.4.4/html/package_geometry_skeleton.html',1,'Skeleton Geometry Support']]],
  ['support_20for_20embedded_20boundary_20construction_24',['Support for Embedded Boundary construction',['../../../samrai/2.4.4/html/package_apputils_embedded_boundary.html',1,'']]],
  ['support_20for_20finite_20element_20operations_20on_20samr_20meshes_25',['Rudimentary Support for Finite Element Operations on SAMR Meshes',['../../../samrai/2.4.4/html/package_algorithm_femutils.html',1,'']]],
  ['support_20for_20moving_20data_20on_20samr_20meshes_26',['Support for Moving Data on SAMR Meshes',['../../../samrai/2.4.4/html/package_transfer_datamovers.html',1,'']]],
  ['support_20for_20patch_20data_20numerical_20routines_20in_20fortran_27',['Support for Patch Data Numerical Routines in FORTRAN',['../../../samrai/2.4.4/html/package_patchdata_fortran.html',1,'']]],
  ['support_20for_20physical_20boundary_20conditions_28',['Support for physical boundary conditions',['../../../samrai/2.4.4/html/package_apputils_boundary.html',1,'']]]
];
