var searchData=
[
  ['package_0',['package',['../../../samrai/2.4.4/html/package_mathematical_operations.html',1,'Mathematical Operations Package'],['../../../samrai/2.4.4/html/package_algorithm.html',1,'The Algorithm Package'],['../../../samrai/2.4.4/html/package_apputils.html',1,'The Application Utilities Package'],['../../../samrai/2.4.4/html/package_geometry.html',1,'The Geometry Package'],['../../../samrai/2.4.4/html/package_hierarchy.html',1,'The Hierarchy Package'],['../../../samrai/2.4.4/html/package_mesh.html',1,'The Mesh Package'],['../../../samrai/2.4.4/html/package_patchdata.html',1,'The Patchdata Package'],['../../../samrai/2.4.4/html/package_solvers.html',1,'The Solver Package'],['../../../samrai/2.4.4/html/package_toolbox.html',1,'The Toolbox Package'],['../../../samrai/2.4.4/html/package_transfer.html',1,'The Transfer Package']]],
  ['parallel_20toolbox_20classes_1',['Parallel Toolbox Classes',['../../../samrai/2.4.4/html/package_toolbox_parallel.html',1,'']]],
  ['patch_20adjacency_20graph_20structures_2',['Patch Adjacency Graph Structures',['../../../samrai/2.4.4/html/package_hierarchy_dlbg.html',1,'']]],
  ['patch_20data_3',['patch data',['../../../samrai/2.4.4/html/package_patchdata_cell.html',1,'Cell Patch Data'],['../../../samrai/2.4.4/html/package_patchdata_edge.html',1,'Edge Patch Data'],['../../../samrai/2.4.4/html/package_patchdata_face.html',1,'Face Patch Data'],['../../../samrai/2.4.4/html/package_patchdata_index.html',1,'Index Patch Data'],['../../../samrai/2.4.4/html/package_patchdata_node.html',1,'Node Patch Data'],['../../../samrai/2.4.4/html/package_patchdata_outeredge.html',1,'Outeredge Patch Data'],['../../../samrai/2.4.4/html/package_patchdata_outerface.html',1,'Outerface Patch Data'],['../../../samrai/2.4.4/html/package_patchdata_outernode.html',1,'Outernode Patch Data'],['../../../samrai/2.4.4/html/package_patchdata_outerside.html',1,'Outerside Patch Data'],['../../../samrai/2.4.4/html/package_patchdata_side.html',1,'Side Patch Data']]],
  ['patch_20data_20and_20variable_20management_4',['AMR Patch Data and Variable Management',['../../../samrai/2.4.4/html/package_hierarchy_variables.html',1,'']]],
  ['patch_20data_20numerical_20routines_20in_20fortran_5',['Support for Patch Data Numerical Routines in FORTRAN',['../../../samrai/2.4.4/html/package_patchdata_fortran.html',1,'']]],
  ['patch_20data_20operations_6',['patch data operations',['../../../samrai/2.4.4/html/package_mathops_cell.html',1,'Cell Patch Data Operations'],['../../../samrai/2.4.4/html/package_patchdata_multiblock.html',1,'Multiblock Patch Data Operations']]],
  ['patch_20data_20support_7',['Array-based Patch Data Support',['../../../samrai/2.4.4/html/package_patchdata_array.html',1,'']]],
  ['patch_20data_20transfer_20operators_8',['Patch Data Transfer Operators',['../../../samrai/2.4.4/html/package_transfer_operators.html',1,'']]],
  ['patch_20geometry_9',['patch geometry',['../../../samrai/2.4.4/html/package_geometry_cartesian_patch_geom.html',1,'Cartesian Patch Geometry'],['../../../samrai/2.4.4/html/package_geometry_multiblock_patch_geom.html',1,'Multiblock Patch Geometry'],['../../../samrai/2.4.4/html/package_geometry_skeleton_patch_geom.html',1,'Skeleton Patch Geometry']]],
  ['patch_20hierarchy_20construction_20and_20adaptive_20meshing_10',['Patch Hierarchy Construction and Adaptive Meshing',['../../../samrai/2.4.4/html/package_mesh_gridding.html',1,'']]],
  ['patch_20hierarchy_20management_11',['patch hierarchy management',['../../../samrai/2.4.4/html/package_hierarchy_patches.html',1,'AMR Patch Hierarchy Management'],['../../../samrai/2.4.4/html/package_hierarchy_multiblock.html',1,'Multiblock AMR Patch Hierarchy Management']]],
  ['patchdata_20package_12',['The Patchdata Package',['../../../samrai/2.4.4/html/package_patchdata.html',1,'']]],
  ['petsc_20vector_20interface_13',['PETSc Vector Interface',['../../../samrai/2.4.4/html/package_solvers_packages_petsc.html',1,'']]],
  ['physical_20boundary_20conditions_14',['Support for physical boundary conditions',['../../../samrai/2.4.4/html/package_apputils_boundary.html',1,'']]],
  ['poisson_20solvers_20on_20a_20samrai_20hierarchy_15',['Poisson solvers on a SAMRAI hierarchy',['../../../samrai/2.4.4/html/package_solvers_poisson.html',1,'']]],
  ['preconditioner_20on_20a_20samrai_20hierarchy_16',['FAC preconditioner on a SAMRAI hierarchy',['../../../samrai/2.4.4/html/package_solvers_FAC.html',1,'']]]
];
